name: Update directory # depois de cadastrar a chave privada no secrets do github, esse workflow vai atualizar o diretório do servidor remoto com o último commit do repositório

on:
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update directory
      uses: appleboy/ssh-action@master
      with:
        host: 64.181.160.224
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/next-crud
          git pull
          yarn build
          docker restart next-crud
